### ISSUE TITLE
Referirea și descrierea în text a fiecărei figuri/diagrame

### ISSUE THREAD

**Issue by cparpalea** [cparpalea/Proiect-TI#15]

**Comment by Davidescu** [comment]
[Referirea si descrierea in text a fiecarei diagrame.docx](https://github.com/cparpalea/Proiect-TI/files/1815903/Referirea.si.descrierea.in.text.a.fiecarei.diagrame.docx)

**Comment by Davidescu** [comment]
[Referirea.si.descrierea.in.text.a.fiecarei.diagrame.docx](https://github.com/cparpalea/Proiect-TI/files/1816801/Referirea.si.descrierea.in.text.a.fiecarei.diagrame.docx)
 Update
