### ISSUE TITLE
Scurtă analiză a tipurilor de aplicații existente din perspectiva temei alese

### ISSUE THREAD

**Issue by cparpalea** [cparpalea/Proiect-TI#4]

**Comment by mihaitaP** [comment]
Pe piata exista diferite moduri de a invata limba Engleza. Vom enunta doar metodele interactive prin intermediul aplicatiilor pentru telefon si cele de pe platformele online cum ar fi:
1)**DUOLINGO** - Aplicatie online + mobile cu diferite nivele de dificultate si exercitii de pronuntie, scriere, vocabular si traducere.
2)**MONDLY** - Aplicatie mobile prin intermediul careia puteti interactiona cu robotul si puteti comunica.
3)**6000 CUVINTE** - Aplicatie mobile pe 3 nivele ce contine 6000 de cuvinte si imagini.
