### ISSUE TITLE
Descrierea generală a implementării (caracteristici așteptate de la aplicație)

### ISSUE THREAD

**Issue by cparpalea** [cparpalea/Proiect-TI#5]

**Comment by Icsyx** [comment]
Această aplicație vine în ajutorul persoanelor care doresc să învețe engleză, sau doar să-și îmbunătățească cunoștințele pe care le dețin deja. Pentru a putea folosi aplicația este nevoie de crearea unui cont, sau de logarea într-un cont deja existent. După ce utilizatorul este logat, acesta poate alege nivelul de dificultate al capitolelor prin care acesta va trece pentru a își îmbunătăți cunoștințele pe care le are. Odată aleasă dificultatea, utilizatorul poate alege ce capitol dorește să urmeze, în ideea că poate reveni asupra unu-i capitol dacă nu a reușit să-și însușească toate cunoștințele prezentate.
La finalul fiecărui capitol utilizatorul v-a susține un test de verificare a cunoștințelor dobândite până în acel moment, urmând ca la finalul tuturor capitolelor acesta să dea un test final din toate capitolele parcurse. Daca testul este promovat, acesta va fi răsplătit cu o diplomă.

**Comment by Icsyx** [comment]
[Prezentare.docx](https://github.com/cparpalea/Proiect-TI/files/1816942/Prezentare.docx)
