### ISSUE TITLE
Identificarea actorilor și a componentelor principale

### ISSUE THREAD

**Issue by cparpalea** [cparpalea/Proiect-TI#7]

**Comment by Icsyx** [comment]
![29134394_1044988782306903_263541428_n](https://user-images.githubusercontent.com/26877376/37478774-d090603a-2883-11e8-9d8b-2e82893fbe26.png)

**Comment by Davidescu** [comment]
Actorii sunt:
-useri;
Componentele principale sunt:
-WEB Server;
-WEB Browser;
-WEB Service Server;
-Desktop/Mobile Application;
-Database Server;
