### ISSUE TITLE
Diagrame UML de use-case

### ISSUE THREAD

**Issue by cparpalea** [cparpalea/Proiect-TI#8]

**Comment by Icsyx** [comment]
![29134394_1044988782306903_263541428_n](https://user-images.githubusercontent.com/26877376/37478675-91925d48-2883-11e8-9094-2adf2b43b718.png)

**Comment by Icsyx** [comment]
![29134394_1044988782306903_263541428_n](https://user-images.githubusercontent.com/26877376/37487709-12fa933e-289b-11e8-8e43-38d24b58ad4c.png)
